
package org.adullact.spring_ws.iparapheur._1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InterfaceParapheurServiceNoMTOM", targetNamespace = "http://www.adullact.org/spring-ws/iparapheur/1.0", wsdlLocation = "file:/home/svast/workspace/iparapheurgetdc/iparapheur.wsdl")
public class InterfaceParapheurServiceNoMTOM
    extends Service
{

    private final static URL INTERFACEPARAPHEURSERVICENOMTOM_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.adullact.spring_ws.iparapheur._1.InterfaceParapheurServiceNoMTOM.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.adullact.spring_ws.iparapheur._1.InterfaceParapheurServiceNoMTOM.class.getResource(".");
            url = new URL(baseUrl, "file:/home/svast/workspace/iparapheurgetdc/iparapheur.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/svast/workspace/iparapheurgetdc/iparapheur.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTERFACEPARAPHEURSERVICENOMTOM_WSDL_LOCATION = url;
    }

    public InterfaceParapheurServiceNoMTOM(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceParapheurServiceNoMTOM() {
        super(INTERFACEPARAPHEURSERVICENOMTOM_WSDL_LOCATION, new QName("http://www.adullact.org/spring-ws/iparapheur/1.0", "InterfaceParapheurServiceNoMTOM"));
    }

    /**
     * 
     * @return
     *     returns InterfaceParapheur
     */
    @WebEndpoint(name = "InterfaceParapheurSoap11NoMtom")
    public InterfaceParapheur getInterfaceParapheurSoap11NoMtom() {
        return super.getPort(new QName("http://www.adullact.org/spring-ws/iparapheur/1.0", "InterfaceParapheurSoap11NoMtom"), InterfaceParapheur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceParapheur
     */
    @WebEndpoint(name = "InterfaceParapheurSoap11NoMtom")
    public InterfaceParapheur getInterfaceParapheurSoap11NoMtom(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.adullact.org/spring-ws/iparapheur/1.0", "InterfaceParapheurSoap11NoMtom"), InterfaceParapheur.class, features);
    }

}
